# Site settings
title: Emacs 中文社区
email: emacs-china@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Emacs 中文社区（测试阶段）
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emacs-china.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  emacs-china

# Build settings
markdown: kramdown
